name: future_riverpod
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.10.4



dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_riverpod: ^3.1.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^4.0.0
  url_strategy: ^0.3.0
  uuid: ^4.5.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^17.1.0
  validators: ^3.0.0
  supabase_flutter: ^2.12.0
  pin_code_fields: ^8.0.1

  flutter_dotenv: ^6.0.0
  gap: ^3.0.1
  google_fonts: ^8.0.1
  google_sign_in: ^7.2.0
  google_sign_in_ios: ^6.3.0
  flutter_svg: ^2.2.3
  shared_preferences: ^2.5.4
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  riverpod_lint: ^3.1.0
  riverpod_generator: ^4.0.0+1




flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  #   - .env

  fonts:
    - family: Hrof
      fonts:
        - asset: assets/fonts/hrof.ttf
    - family: Hazm
      fonts:
        - asset: assets/fonts/hazm.ttf
    - family: Zain
      fonts:
        - asset: assets/fonts/zain.ttf